### PR TITLE
Added didDeploy hook, and make activate hook add activatedRevisionKey to context.

### PR DESCRIPTION
**Pull request by lukemelia**
The didDeploy hook works with a configurable `didDeployMessage` which is output when the hook runs.

### CODE REVIEW

**Comment by lukemelia** [comment]
One thing this allows, is outputting a preview URL, which requires knowledge of server implementation. For example, a potential excerpt from `config/deploy.js`:

``` js
   ENV.redis.didDeployMessage = function(context) {
      if (context.revisionKey && !context.activatedRevisionKey) {
        return "Deployed but did not activate revision " + context.revisionKey + ".\n"
             + "To preview:\n"
             + "https://" + domain + "/apps/?manifest_id=" + context.revisionKey + "\n"
             + "To activate:\n"
             + "ember activate " + context.revisionKey + " --environment=" + process.env.DEPLOY_ENVIRONMENT + "\n";
      }
    }
```

**Comment by achambers** [comment]
@lukemelia Could we put the `DEPLOY_ENVIRONMENT` in the context?  This might be a good use case for the `commandLineArgs` object that is added to the context by the command?

**Comment by achambers** [comment]
@lukemelia Are you planning on raising a PR for this change against the master repo?

**Comment by lukemelia** [comment]
Will update and reopen against upstream

**Pull request closed without merging**
